apiVersion: v1
kind: Service
metadata:
  name: collapser-proxy
  labels: {app: collapser-proxy}
spec:
  # The Service points at the Collapser container in the same pod as the backend.
  selector: {app: hello-backend}
  ports:
    - {name: grpc-collapser, port: 50052, targetPort: grpc-collapser}
    - {name: http-metrics, port: 2112, targetPort: metrics}
